# רשימת משתמשים מורשים
# הוסף את מזהי המשתמשים של טלגרם (user_id)
authorized_users:
  - 123456789  # דוגמה - החלף במזהה האמיתי שלך
  
# האם לאפשר גישה רק למשתמשים מורשים
enforce_authorization: true

# הודעת שגיאה למשתמשים לא מורשים
unauthorized_message: "⛔ אין לך הרשאה להשתמש בבוט זה. אנא פנה למנהל המערכת."
